use company_9415419
1
SELECT TOP 1 SUM(SALARY) AS TOTAL,DNAME
FROM employee,department 
WHERE DNO=Dnumber
GROUP BY DNAME ORDER BY TOTAL DESC;


SELECT E.fname, E.minit, E.lname, E.[Address],E.Ssn,E.Super_Ssn, S.Fname as SupFName, S.lname as SupLName, (E.salary)
FROM employee as E, employee as S
WHERE E.Super_Ssn = S.Ssn AND E.SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEE)
order by E.fname asc;

2
SELECT (salary), fname,DNAME
FROM [EMPLOYEE],DEPARTMENT WHERE DNO=DNUMBER AND SALARY IN (SELECT max(SALARY) FROM EMPLOYEE)

SELECT FNAME, SALARY, DNO, DNAME
FROM EMPLOYEE INNER JOIN DEPARTMENT ON EMPLOYEE.DNO=DEPARTMENT.DNUMBER WHERE SALARY IN(SELECT MAX(SALARY) FROM EMPLOYEE)


3
SELECT E.Fname,E.Minit,E.Lname,E.Address,E.Ssn, E.Super_ssn, E.Salary,EMP.FNAME as "Supervisor Name"
FROM EMPLOYEE as E, EMPLOYEE AS EMP WHERE E.SUPER_SSN=EMP.SSN AND E.Salary IN(SELECT MIN(Salary) FROM EMPLOYEE)

